### ISSUE TITLE
An unexpected error has occured and the app had to be closed

### ISSUE THREAD

**Issue by naveenjohnsonv** [shadow578/YetAnotherVideoPlayer#5] opened 2020-05-26 08:05 UTC
https://pastebin.com/S2gYUKfY
Using yavp-release-973, opening app works without issues until I enable storage permissions. Then trying to open app shows this error.

**Comment by ghost** [comment] 2020-05-30 19:36
> https://pastebin.com/S2gYUKfY
> Using yavp-release-973, opening app works without issues until I enable storage permissions. Then trying to open app shows this error.

Same for me

**Comment by shadow578** [comment] 2020-05-31 17:21
Seems to be a bug with the MediaMetadataRetriver (which I use to retrive video title and duration). The next release should fix that (will release tomorrow or so, am still testing a bit)

**Comment by shadow578** [comment] 2020-06-01 15:33
I just released YAVP 1003 and hope it fixes this issue. Please check it out and tell me if the issue persists (i hope not 😄 )

**Comment by naveenjohnsonv** [comment] 2020-06-02 13:50
Yes the crashes are fixed! Unfortunately, media is still not being shown on the app, i can only open on YAVP via another app.

**Comment by shadow578** [comment] 2020-06-06 09:31
I'm currently trying to find out why this is happening, but can't really reproduce it... Could you tell me what phone model and android version you're running? I found that HTC is known for changing stuff against the spec, so this might be the cause.

**Comment by naveenjohnsonv** [comment] 2020-06-10 13:28
I'm using a custom ROM on my K20 Pro and it's stock Android 10. It might be a problem with Android 10 devices specifically?

**Comment by 0xlne** [comment] 2020-06-16 21:40
I'll echo @naveenjohnsonv with media (both video & audio) not shown, but launching media from a file browser works.
Device: Samsung Galaxy Note 10+/ Android 10

**Comment by shadow578** [comment] 2020-06-26 20:42
Hi, sorry for taking so long to reply. 
I think this issue has to do with androids new scoped storage system. 
You can download a preview apk that possibly fixes this [here](https://github.com/shadow578/YetAnotherVideoPlayer/blob/dev/preview-apk/yavp-preview.apk?raw=true) (and also does some other things :))
note that the app will prompt you to update, just ignore that for now.

**Comment by shadow578** [comment] 2020-07-04 11:30
This issue should be resolved in yavp 1108. 
I'll close the issue for now, tho if it still persists, feel free to reopen it.

**Closed as completed by shadow578** 2020-07-04 11:30 UTC
